#!/usr/bin/env bash

# $1 = topic
# $2 = time spended

seconds_since_start=$(( $(date +'%s') - $(date --date='2022-05-31 00:00:01' +'%s') ))
days_since_start=$(( $seconds_since_start / 60 / 60 / 24 ))
name_today=$( echo "$days_since_start[$(date +'%d.%m.%Y')]" )

today_path="/home/alexs/learn/1000days/0_100/${name_today}.md"
printf "## Day $days_since_start ($1 | $2) \n\n\n" > $today_path
nvim +3 $today_path
 

